apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-named-ports
  labels:
    kubernetes.courselabs.co: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-named
  template:
    metadata:
      labels:
        app: whoami-named
    spec:
      containers:
        - name: whoami
          image: sixeyed/whoami:21.04
          ports:
            - name: http-web
              containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              value: "80"
