apiVersion: v1
kind: Namespace
metadata:
  name: path-types-exact
  labels:
    kubernetes.courselabs.co: ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-health
  namespace: path-types-exact
  labels:
    kubernetes.courselabs.co: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-health
  template:
    metadata:
      labels:
        app: api-health
        kubernetes.courselabs.co: ingress
    spec:
      containers:
      - name: whoami
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: health-svc
  namespace: path-types-exact
  labels:
    kubernetes.courselabs.co: ingress
spec:
  selector:
    app: api-health
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exact-ingress
  namespace: path-types-exact
  labels:
    kubernetes.courselabs.co: ingress
spec:
  rules:
  - host: exactpath.local
    http:
      paths:
      - path: /api/health
        pathType: Exact
        backend:
          service:
            name: health-svc
            port:
              number: 8080
      - path: /api/health/check
        pathType: Exact
        backend:
          service:
            name: health-svc
            port:
              number: 8080
