apiVersion: v1
kind: Namespace
metadata:
  name: path-types
  labels:
    kubernetes.courselabs.co: ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: path-types
  labels:
    kubernetes.courselabs.co: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        kubernetes.courselabs.co: ingress
    spec:
      containers:
      - name: whoami
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: path-types
  labels:
    kubernetes.courselabs.co: ingress
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefix-ingress
  namespace: path-types
  labels:
    kubernetes.courselabs.co: ingress
spec:
  rules:
  - host: pathtest.local
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: web-app-svc
            port:
              number: 80
