# NOTE: This is an example IngressClass for Traefik.
# To use this, you would need Traefik Ingress Controller installed.
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  labels:
    kubernetes.courselabs.co: ingress
spec:
  controller: traefik.io/ingress-controller
---
# Example with parameters
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-external
  labels:
    kubernetes.courselabs.co: ingress
spec:
  controller: traefik.io/ingress-controller
  parameters:
    apiGroup: traefik.io
    kind: IngressRoute
    name: external-web
