apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshoot-demo
  labels:
    kubernetes.courselabs.co: affinity-ckad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: troubleshoot-demo
  template:
    metadata:
      labels:
        app: troubleshoot-demo
        kubernetes.courselabs.co: affinity-ckad
    spec:
      affinity:
        nodeAffinity:
          # This label doesn't exist in most clusters!
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ultra-fast  # This value doesn't exist
      containers:
      - name: app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
